name: lint_python

on:
  pull_request:
  push:

jobs:
  lint_python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip setuptools ruff
          pip install -e ".[dev]"

      - name: Code formatting check
        run: black --check .

      - name: Spell check
        run: codespell --ignore-words-list="ro" --skip="*.json,*.lock,./.git"

      - name: Ruff check
        run: ruff check .

      - name: Type checking with mypy
        run: mypy --non-interactive .

      - name: Copy CKEditor files
        run: cp -R django_ckeditor_5 example/blog

      - name: Change directory to example
        run: cd example

      - name: Install dependencies in example
        run: pip install -e ".[dev]"

      - name: Run tests with pytest
        run: pytest example/blog

      - name: Print Python version
        run: python --version

      - name: Print pip version
        run: pip --version

      - name: List installed pip packages
        run: pip list

#      - name: Check for vulnerabilities
#        run: safety check

